# Generated by Django 5.0.6 on 2024-07-22 13:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Barcode', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('initial_quantity', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Myteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('team_note', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team_images/')),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('registration', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('representative', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('items', models.CharField(blank=True, max_length=10, null=True)),
                ('team_mode', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Myuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.BooleanField(blank=True, null=True)),
                ('privacy', models.BooleanField(blank=True, null=True)),
                ('receive_news', models.BooleanField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(default='avtar/avtar.png', upload_to='avtar/')),
                ('csrf_token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('stockin', 'Stockin'), ('stockout', 'Stockout'), ('adjust', 'Adjust'), ('item', 'Item'), ('attribute', 'Attribute'), ('partner', 'Partner')], max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=100)),
                ('attribute_value', models.CharField(max_length=100)),
                ('attribute_type', models.CharField(blank=True, max_length=100, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.item_information')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.myteam')),
            ],
        ),
        migrations.AddField(
            model_name='item_information',
            name='myteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.myteam'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('memo', models.TextField(max_length=500)),
                ('favorite', models.BooleanField(blank=True, null=True)),
                ('foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.myteam')),
            ],
        ),
        migrations.AddField(
            model_name='myteam',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.myuser'),
        ),
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('business_regd_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('company_representative', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField(unique=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Permiteduser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(blank=True, choices=[('admin', 'Admin'), ('viewer', 'Viewer')], max_length=30, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission_status', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=10)),
                ('additional_permission', models.CharField(blank=True, max_length=50, null=True)),
                ('myteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.myteam')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('permissions', models.JSONField()),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.myteam')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('memo', models.TextField(max_length=500)),
                ('favorite', models.BooleanField(blank=True, null=True)),
                ('foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.myteam')),
            ],
        ),
        migrations.CreateModel(
            name='Stockout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('initial_quantity', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
                ('memo', models.TextField(blank=True, max_length=500, null=True)),
                ('rack_no', models.CharField(blank=True, null=True)),
                ('myteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.item_information')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockouts', to='myapp.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Stockin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=100)),
                ('initial_quantity', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
                ('memo', models.TextField(blank=True, max_length=500, null=True)),
                ('rack_no', models.CharField(blank=True, null=True)),
                ('myteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.item_information')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockins', to='myapp.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Adjust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField(blank=True, max_length=500, null=True)),
                ('initial_quantity', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rack_no', models.CharField(blank=True, null=True)),
                ('myteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.item_information')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjusts', to='myapp.transaction')),
            ],
        ),
    ]
