# Generated by Django 5.0.6 on 2024-07-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_information',
            name='feature_vector',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
