# Generated by Django 5.0.6 on 2024-08-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_item_information_feature_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='present_quantity',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
