# Generated by Django 5.0.6 on 2024-08-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_item_information_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemattribute',
            name='attribute_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemattribute',
            name='attribute_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
